### PR TITLE
Documentation laplacian

### PR DESCRIPTION
**Pull request by maximilian-salomon**
fix issue #10

### CODE REVIEW

**Review by cwehmeyer — CHANGES_REQUESTED** [review]
Please refer to other functions to see how docstrings should be formatted.

**Comment by maximilian-salomon** [comment]
I changed some Style-Issues. Think it's better now. If you want to have more details, let me know

**Comment by maximilian-salomon** [comment]
Little remainder for open PR. Can i close this?

**Review by cwehmeyer — CHANGES_REQUESTED** [review]
Docstrings do not go in front of the functions

**Pull request closed without merging**
